apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-flask
        image: asia.gcr.io/research-tskzh/gke-test:latest
        ports:
        - containerPort: 5000
